var gaji = 4500000;
var transportasi = 10000;
var hari = 24;
var infak = 50000;
var bpjs = 250000;
var pajak = 0.025;
var hasilpajak = pajak*gaji;
var hasiltunjangan = transportasi*hari;
var hasilpotongan = hasilpajak+bpjs+infak;
var perhitungangaji = gaji-hasilpotongan+hasiltunjangan;              

console.log(" gaji kotor = " + gaji);
console.log("=====================");
console.log("potongan pajak 2,5% = " + (hasilpajak));
console.log("potongan bpjs = " + bpjs);
console.log("potongan infak = " + infak);
console.log("=====================");
console.log("total potongan = " + (hasilpajak+bpjs+infak));
console.log("=====================");
console.log("tunjangan transportasi = " + transportasi);
console.log("total hari kerja = " + hari);
console.log("=====================");
console.log("total tunjangan = " + (transportasi*hari));
console.log("=====================");
console.log("perhitungan gaji = ");
console.log("gaji kotor - potongan) + tunjangan");
console.log("("+gaji+"-"+hasilpotongan+") + "+hasiltunjangan);
console.log("=====================");
console.log("gaji bersih = " +"Rp."+ perhitungangaji); 